lasttask/cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

lasttask/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search_app/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('credentials/',include('credentials.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

lasttask/search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'
urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),
]

lasttask/shop/urls.py
from django.urls import path, include
from . import views
from .views import load_courses

app_name='shop'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('school/',views.school,name='school'),
    path('school/schoolform/',views.scholform,name='schoolform'),
    path('shop/<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('shop/<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),
    path('add/', views.person_create_view, name='person_add'),
    path('<int:pk>/', views.person_update_view, name='person_change'),
    path('ajax/load-courses/', views.load_courses, name='ajax_load_courses'),

]

lasttask/cart/models.py
from django.db import models
from shop.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table="Cart"
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

lasttask/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import  Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))


def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

lasttask/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Oleo+Script&display=swap" rel="stylesheet">
     <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">-->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>-->

    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadesciption %}{% endblock %}">
    <title>{%block title %}{% endblock %}</title>
</head>
<body class="d-flex flex-column min-vh-100">
<div>


{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
<div>
{% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
</div>
</body>
</html>

lasttask/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  This is the cart page. proceed to rewiew your items and place the order.
{% endblock %}
{% block title %}
    Cart-Picman @PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
  <div class="text-center">
    <br>
    <h1 class="text-center my_title">
      Your have no bookings yet!
    </h1>
    <br>
    <p class="text-center">
      Please Click <a href="{% url 'shop:allProdCat' %}">Here</a> to continue Booking.
    </p>

  </div>
</div>
{% else %}
<div>
  <div class="text-center">
    <br>
    <h1 class="text-center my_title">
      Your Bookings
    </h1>
    <br>
  </div>
</div>
<div class="row mx-auto">
  <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
      <thead class="my_custom_thead">
      <tr>
        <th colspan="5">
          Your Items
        </th>
      </tr>
      </thead>
      <tbody>
      {% for cart_item in cart_items %}
      <tr>
        <td>
          <a href=""><img src="{{cart_item.product.image.url}}" style="width:150px;height:100px;" alt="" class="float-left rounded custom_image"> </a>
        </td>
        <td class="text-left">
          {{cart_item.product.name}}
          <br>
          SKU:{{cart_item.product.id}}
          <br>
          Price: $ {{ cart_item.product.price }}
          <br>
          Qty :{{cart_item.quantity}} x $ {{cart_item.product.price}}
          <br>
        </td>
        <td>
          $ {{cart_item.sub_total}}
        </td>
        {% if cart_item.quantity < cart_item.product.stock  %}
        <td>
           <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
          &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon" > </i></a>
          &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"> </i></a>
        </td>
        {% else %}
         <td>
           &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon" > </i></a>
           &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"> </i></a>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
  <table class="table my_custom_table">
    <thead class="my_custom_thead">
      <tr>
        <th>
          Checkout
        </th>
      </tr>
    </thead>
    <tbody>
    <tr>
      <td>
        Please review your shoping cart items before proceeding with the booking.
      </td>
    </tr>
    <tr>
      <td class="text-left">
        Your Total is : <strong>{{ total }}</strong>
      </td>
    </tr>
    </tbody>
  </table>
  <div class="mx-auto">
    <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Booking</a>
    <a href="" class="btn btn-secondary btn-block my_custom_button" >Pay Now</a>
  </div>
  {% endif %}
</div>
</div>
</div>
{% endblock %}

lasttask/templates/category.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<section  align="center" xmlns="http://www.w3.org/1999/html">
    <div  align="center"">
        <a href="school/"><button>Click Here </button></a>
    </div>
</section>
<!--{% if category %}-->

<!--    <div class="container">-->
<!--      <div class="row my_row_class">-->
<!--          <div class="mx-auto">-->

<!--&lt;!&ndash;        <p><a href="{% url 'shop:allProdCat' %}">OUR Product Collections </a></p>&ndash;&gt;-->
<!--      </div>-->
<!--      </div>-->
<!--    </div>-->
<!--{% endif %}-->
<!--<div class="mx_auto">-->
<!--    {% if category %}-->
<!--        <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" width="1350" height="500">-->
<!--</div>-->
<!--    <br>-->
<!--<div>-->
<!--      <h1 class="text-center my_title">{{category.name}}</h1>-->
<!--      <p class="text-justify">{{category.description}}</p>-->
<!--</div>-->
<!--    {% else %}-->
<!--<div >-->
<!--<img class="my_image my_image_padding" src="{% static 'img/banner1.png' %}" alt="our products" width="1350">-->
<!--</div>-->
<!--<br>-->
<!--<div class="container">-->
<!--  <h1 class="text-center my_title">Our Products Collections</h1>-->
<!--  <p style="text-align:center" class="tetx-justify">we have a verity of photography products .wedding photography,fashion photography,potrait photography etc...-->
<!--  </p>-->
<!--</div>-->
<!--    {% endif %}-->
<!--<div class="container">-->
<!--  <div class="row mx_auto">-->
<!--    {% for product in products.object_list %}-->
<!--    <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">-->
<!--        <div class="card text-center" style="min-width:18rem;">-->
<!--            <a href="{{product.get_url}}"><img class="card-img-top my_images" src="{{product.image.url}}" alt="{{product.name}}" height="190px"></a>-->
<!--        <div class="card-body">-->
<!--            <h4>{{product.name}}</h4>-->
<!--            <p>{{product.price}}</p>-->
<!--        </div>-->
<!--        </div>-->
<!--    </div>-->
<!--    {% endfor %}-->
<!--  </div>-->
<!--    <div class="mx-auto">-->
<!--        {% if products.paginator.num_pages > 1 %}-->

<!--        <hr>-->
<!--        <div class="text-center">-->
<!--            {% for pg in products.paginator.page_range%}-->
<!--            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--        {% endif %}-->
<!--    </div>-->
<!--    <br>-->
<!--</div>-->
{% endblock %}

lasttask/templates/footer.html
{% load static %}
<footer >
  <div style="padding-top:50px;">
<!--<div class="footer navbar-fixed-bottom my-footer">-->
    <div class="navbar fixed-bottom" >
  <p  style="position:absolute;left:41%;" class="text-center">&copy;Picman pvt ltd. All rights Reserved</p>
</div>
</div>
</footer>

lasttask/templates/hello.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="background-color:yellow">
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Online Movie Store
  </a>
    <a  href="add/"><button>Add Movie</button></a>
</nav>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-interval="20">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item" data-interval="20">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<img src="C:\Users\ADHUL SHAJU MECHERY\Pictures\Video Projects\WhatsApp Image 2021-06-06 at 3.16.19 PM.jpeg"  alt="demmycontent" style="width:180px;height:220p" align="">
{% block body %}
{% endblock %}
</body>
</html>

lasttask/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body style="background-color:#4d8f75; padding:120px">
<h1 style="text-align:center ;padding:00px">Login</h1>
<form method="post" action="login">
    {% csrf_token %}
    <table align="center" cellpadding="3">
        <tr>
             <td>Username</td>
            <TD><input type="text" name="username" placeholder="Enter the username"></TD>
        </tr>
         <tr>
             <td>Password</td>
             <TD><input type="password" name="password" placeholder="Enter the Password"></TD>
         </tr>
        <tr>
            <td colspan="2" align="center"><input type="submit" name="Login" value="Login">
                <input type="reset" name="reset" value="Reset"></td>
            <td><a href="register"><input type="button"  value="Register" ></a> </td>
        </tr>
    </table>
</form>
{% for msg in messages %}
<h3 style="color:red;text-align:center"> {{msg}}</h3>
{% endfor %}
</body>
</html>

lasttask/templates/navbar.html
{% load static %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
<!--        <li class="nav-item">-->
<!--          <a class="nav-link active" aria-current="page" href="#">Home</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'shop:allProdCat' %}">Picman</a>-->
<!--        </li>-->
        <li class="nav-item">
            {% if user.is_authenticated %}
          <li class="nav-link">Hello {{user.first_name}}</li>
          <li ><a class="nav-link" href="credentials/logout">Logout</a></li>
          {% else %}
          <li class="active"><a class="nav-link" href="credentials/register">Register</a></li>
          <li ><a class="nav-link" href="credentials/login">Login</a></li>
          {% endif %}
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Department
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">Computer Science</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">Commerce</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Medicine">Medical Science</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/The_arts">Arts</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Mechanical">Mechanical</a></li>

          </ul>
        </li>
<!--        {% if item_count > 0 %}-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link activate" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>-->
<!--        </li>-->
<!--        {% endif %}-->
<!--        <ul style="align:center">-->
<!--            <div>-->
<!--            <img src="{% static 'img/logo2.png'%}"width="40px" height="40px" align="center">-->
<!--            </div>-->
<!--        </ul>-->
      </ul>

<!--      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">-->
<!--          {% csrf_token %}-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">-->
<!--        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>-->
<!--      </form>-->
    </div>
  </div>
</nav>
<!--<nav>-->
<!--    <ul>-->
<!--        <li><a href="{% url 'shop:allProdCat' %}">All Products</a></li>-->
<!--        {% for cat in links %}-->
<!--        <li><a href="{{cat.get_url}}">{{cat.name}}</a> </li>-->
<!--        {% endfor %}-->
<!--        <li> Your Cart()</li>-->
<!--    </ul>-->
<!--</nav>-->

lasttask/templates/order_confirmed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Confirmed</title>
</head>
<body>
<p>{{ order_confirmed }}</p>
<a href="/">Return to Home page</a>
</body>
</html>

lasttask/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
  {% if category %}
    {{product.name }} - ABC Store
    Picman - CAPTURE YOUR MOMENTS
  {% endif %}
{% endblock %}

{% block content %}
<div class="row my_product_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shop:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.categry}}</a> | {{product.name}}</p>
    </div>
</div>
<div class="container">
    <br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem">
                <img src="{{ product.image.url }}" alt="{{product.name}}" width="500">
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title">{{product.name}}</h1>
                <p>${{product.price}}</p>
                <p class="my_title">Product Description</p>
                <p class="text-justify my_prod_text">{{product.description}}</p>
                {% if product.stock <= 0 %}
                <p class="text-justify my_prod_text"><b>Out of stock</b></p>
                {% else %}
                <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}"> Book now</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

lasttask/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
</head>
<body>

<h2 align="center">Registration</h2>
<form action="register" method="post" align="center">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter your username"><br>
    <input type="text" name="first_name" placeholder="Enter your first name"><br>
    <input type="text" name="last_name" placeholder="Enter your last name"><br>
    <input type="email" name="email" placeholder="Enter your email"><br>
    <input type="password" name="password" placeholder="Enter your password"><br>
    <input type="password" name="password1" placeholder="Confirm your password"><br>
    <input type="submit">
</form>
{% for msg in messages %}
<h3 style="color:red;text-align:center"> {{msg}}</h3>
{% endfor %}
</body>
</html>

lasttask/templates/scform.html
{% extends 'base.html' %}
{% load static %}



{% block content %}


<h2 align="center">School Form</h2>
<form action="" method="post" align="center">
    {% csrf_token %}
    <span>NAME : </span><input type="text" name="name" placeholder="Enter your Name"><br/><br/>
    <span>DOB : </span><input type="date" name="dob" placeholder="Enter your Date of Birth"><br/><br/>
    <span>AGE : </span><input type="number" name="age" placeholder="Enter your Age"><br/><br/>
    <span>GENDER : </span><input type="text" name="gender" placeholder="Enter your Gender"><br/><br/>
    <span>PHONE NUMBER : </span><input type="number" name="phone" placeholder="Enter your Phone Number"><br/><br/>
    <span> EMAIL ID : </span><input type="email" name="email" placeholder="Enter your Email Id"><br/><br/>
    <span> ADDRESS : </span><input type="text" name="address" placeholder="Enter your Address"><br/><br/>
    <input type="submit">
</form>


{% for msg in messages %}
<h3 style="color:red;text-align:center"> {{msg}}</h3>
{% endfor %}

{% endblock %}

lasttask/templates/schoolformbutton.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<section  align="center" xmlns="http://www.w3.org/1999/html">
    <div  align="center"">
        <a href="/add/"><button>School Form Fill </button></a>
    </div>
</section>
{% endblock %}

lasttask/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    we have variety of products.
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for :<b>"{{query}}"</b></p>
</div>
<div class="container">
  <div class="row mx_auto">
    {% for product in products %}
    <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
        <div class="card text-center" style="min-width:18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top my_images" src="{{product.image.url}}" alt="{{product.name}}"></a>
        <div class="card-body">
            <h4>{{product.name}}</h4>
            <p>{{product.price}}</p>
        </div>
        </div>
    </div>
    {% empty %}
      <div class="row mx-auto">
          <p class="text-center my_center my_search_text">0 results found</p>
      </div>
      {% endfor %}
  </div>
</div>
{% endblock %}