lasttask/cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

lasttask/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search_app/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('credentials/',include('credentials.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

lasttask/shop/urls.py
from django.urls import path, include
from . import views
from .views import load_courses

app_name='shop'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('school/',views.school,name='school'),
    path('school/schoolform/',views.scholform,name='schoolform'),
    path('shop/<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('shop/<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),
    path('add/', views.person_create_view, name='person_add'),
    path('<int:pk>/', views.person_update_view, name='person_change'),
    path('ajax/load-courses/', views.load_courses, name='ajax_load_courses'),

]

lasttask/shop/models.py
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])
    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shop:prodCatdetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return '{}'.format(self.name)


class Department(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Course(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name
class Material(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Person(models.Model):
    name = models.CharField(max_length=124)
    dob = models.DateField()
    age = models.IntegerField()
    Gender_CHOICES = (
        ('M', 'Male'), ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=Gender_CHOICES)
    phone = models.IntegerField()
    mail = models.EmailField()
    address = models.CharField(max_length=200)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, blank=True, null=True)
    Purpose_CHOICES = (
        ('A','Enquiry'),('B','Place Order'),('C','Return'),('D','Payment Issues'),
    )
    purpose = models.CharField(max_length=1,choices=Purpose_CHOICES)
    # Material_CHOICES = (
    #     ('A','Debit Note Book'),('B','Pen'),('C','Exam Papers'),
    # )
    # materials = models.CharField(max_length=255)
    debit_notebook = models.BooleanField(default=False)
    pen = models.BooleanField(default=False)
    exam_papers = models.BooleanField(default=False)

# class Details(models.Model):
#     name = models.ForeignKey(Person,on_delete=models.SET_NULL,blank=True,null=True)
#     dob = models.DateField()
#     age = models.IntegerField()
#     Gender_CHOICES = (
#         ('M', 'Male'), ('F', 'Female'),
#     )
#     gender = models.CharField(max_length=1, choices=Gender_CHOICES)
#     phone = models.IntegerField()
#     mail = models.EmailField()
#     address = models.CharField(max_length=200, blank=True)



    def __str__(self):
        return self.name

lasttask/templates/persons/course_dropdown_list_options.html
<option value="">---------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}

lasttask/templates/persons/home.html
<!doctype html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dependent Dropdown in Django</title>
</head>
<body>

<h2>Student Detail Form</h2>

<form method="post" id="personForm" data-courses-url="{% url 'shop:ajax_load_courses' %}">
    {% csrf_token %}
    <table>
   <tr> <td><label>Name &nbsp;</label></td>
        <td>{{ form.name }}</td>
   </tr>
            <tr></tr>
    <tr>
        <td>
            <label>Date of Birth &nbsp;</label>
        </td>
        <td>
            <input type="date" name="dob" id="{{ form.dob.id_for_label }}">
        </td>
    </tr>
            <tr></tr>
    <tr>
        <td>
            <label>Age</label>
        </td>
        <td>
            {{form.age}}<br/>
        </td>
    </tr>
            <tr></tr>
    <tr>
        <td>
            <label>Gender &nbsp;</label>
        </td>
        <td>
            {{form.gender}}
        </td>
    </tr>
            <tr></tr>
    <tr>
        <td>
            <label>Address &nbsp;</label>
        </td>
        <td>
            {{form.address}}
        </td>
    </tr>
            <tr></tr>
    <tr>
        <td>
            <label>Phone Number &nbsp;</label>
        </td>
        <td>
            {{form.phone}}
        </td>
    </tr>
            <tr></tr>
    <tr>
        <td>
            <label>Email &nbsp;</label>
        </td>
        <td>
            {{form.mail}}
        </td>
    </tr>
            <tr></tr>
    <tr>
        <td>
            <label>Purpose &nbsp;</label>
        </td>
        <td>
            {{form.purpose}}
        </td>
    </tr>
            <tr></tr>
    <tr>
        <td>
            <label>Department &nbsp;</label>
        </td>
        <td>
            {{form.department}}
        </td>
</tr>
            <tr></tr>
    <tr>
        <td>
            <label>Course &nbsp;</label>
        </td>
        <td>
            {{form.course}}
        </td>
    </tr>
            <tr></tr>
    <tr>
        <td>
            <label>Materials Provide:</label>
        </td>
        <td>
            <input type="checkbox" name="debit_notebook" id="{{ form.debit_notebook.id_for_label }}" {% if form.debit_notebook.value %}checked{% endif %}>
  <label for="{{ form.debit_notebook.id_for_label }}">Debit Note Book</label><br>
  <input type="checkbox" name="pen" id="{{ form.pen.id_for_label }}" {% if form.pen.value %}checked{% endif %}>
  <label for="{{ form.pen.id_for_label }}">Pen</label><br>
  <input type="checkbox" name="exam_papers" id="{{ form.exam_papers.id_for_label }}" {% if form.exam_papers.value %}checked{% endif %}>
  <label for="{{ form.exam_papers.id_for_label }}">Exam Papers</label><br>
        </td>
    </tr>
</table>







<!--<label>Materials Provided:</label>&nbsp;&nbsp;-->
<!--  {{ form.debit_note_book }} Debit Note Book &nbsp;-->
<!--  {{ form.pen }} Pen &nbsp;-->
<!--  {{ form.exam_papers }} Exam Papers<br>-->
    <input type="submit" value="Submit">
</form>

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-success">
      {{ message }}
        <a href="/">Return to Home</a>
    </div>
  {% endfor %}
{% endif %}


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_department").change(function () {
        const url = $("#personForm").attr("data-courses-url");  // get the url of the `load_cities` view
        const departmentId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'department_id': departmentId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_course").html(data);  // replace the contents of the city input with the data that came from the server
                /*
                let html_data = '<option value="">---------</option>';
                data.forEach(function (course) {
                    html_data += `<option value="${course.id}">${course.name}</option>`
                });
                console.log(html_data);
                $("#id_course").html(html_data);
                */
            }
        });

    });
</script>

</body>
</html>